export const AUTH_API_LOADING = '@AUTH/AUTH_API_LOADING';
export const AUTH_API_FAILED = '@AUTH/AUTH_API_FAILED';
export const CHANGE_SCROLL_FOCUS = '@AUTH/CHANGE_SCROLL_FOCUS';
export const CHANGE_LOGIN_STATE = '@AUTH/CHANGE_LOGIN_STATE';
export const LOGIN_SUCCESS = '@AUTH/LOGIN_SUCCESS';
export const SUBSCRIBE_WAITLIST_SUCCESS = '@AUTH/SUBSCRIBE_WAITLIST_SUCCESS';